### ISSUE TITLE
MySqlConnector unix_socket should check for not empty

### ISSUE THREAD

**Issue by ryantxr** [leomarquine/php-etl#12]
In MySqlConnector you have:

```php
        if (isset($unix_socket)) {
            $dsn['unix_socket'] = $unix_socket;
        }
```

I think it really should be this:
```php
        if (!empty($unix_socket)) {
            $dsn['unix_socket'] = $unix_socket;
        }
```
The standard database config file that comes with Laravel defines unix_socket but leaves it empty. The code you have now sees that unix_socket is set and tries to use it even though it is an empty string.

I will do a pull request if you like.

**Comment by leomarquine** [comment]
I just tagged a new release that should fix it.
