### ISSUE TITLE
Add customizer collumn

### ISSUE THREAD

**Issue by Claonilton** [leomarquine/php-etl#13]
Hi, need customizer with one collumn in php-etl with my configuration Extract, is possible? 

Example
In Model with Xml: 
`
'organization'=>'parameter[0]', 
'field01'=>'field01',
'field02'=>'field02' ...
`
organization not exist in my XML, is customizer is possible?

**Comment by leomarquine** [comment]
You can create a custom transformer that pushes the organization field to the data flow.
