### ISSUE TITLE
Resolving ETL from Laravel's IoC Container makes nonfunctioning instance

### ISSUE THREAD

**Issue by jimmypuckett** [leomarquine/php-etl#22]
When I manually make an ETL instance

```php
(new Marquine\Etl\Etl)->extract('csv', './file.csv')->transform('rename_columns', ['columns' => ['email_address' => 'email']])->toArray()
```

I get...

```php
[
     [
       "id" => "1",
       "name" => "Name 1",
       "email" => "email@1.com",
     ],
     //...
]
```

but when use the IoC...

```php
app(Marquine\Etl\Etl::class)->extract('csv', './file.csv')->transform('rename_columns', ['columns' => ['email_address' => 'email']])->toArray()
```

I get an error...

```php
InvalidArgumentException with message 'The step [csv] is not a valid extractor.'
```

**Comment by ecourtial** [comment]
Hi @jimmypuckett  if you want, we forked the library [here](https://github.com/wizaplace/php-etl) and we fixed some issues and added some features. The changelog is available [here](https://github.com/wizaplace/php-etl/blob/master/changelog.MD). Our objective is to keep this great library alive. If you find any bug or want to contribute to keep the package alive, do not hesitate!
