### ISSUE TITLE
Replace XMLReader with SimpleXML

### ISSUE THREAD

**Issue by sekjal** [leomarquine/php-etl#24]
SimpleXML is available by default in PHP since 5.1.3, and allows XPath queries.  Switching the XML Extractor to using this module has a number of advantages:

- Simpler code base; the extract() function no longer requires helper functions per node
- Filtering from within the _loop_ param; it becomes possible to only include nodes that match various criteria, which can be useful in certain XML structures
- parent node querying from _columns_; useful when trying to convert nested documents to a flat relational structure

Performance seems to be comparable in my limited testing.

If this is a valuable enhancement to the existing XML extractor, I can submit a pull request.  I could package this as a new extractor type ("simplexml") if that would be better for backward compatibility.

**Comment by leomarquine** [comment]
The problem with SimpleXML is that we need to load all the xml in memory and we cant take advantage of generators like we do in the current implementation.

But, if necessary, we can have both extractors.

**Comment by sekjal** [comment]
I'm seeing that problem now... even with a modestly sized XML document (~500MB), PHP starts to choke.  I really like the ability to do full xpath on the loop and the the columns, but there is definitely a cost.  Going to mark this as closed, since replacing the current XML Extractor is not appropriate.
