### ISSUE TITLE
Callback transformer

### ISSUE THREAD

**Issue by kasperg** [leomarquine/php-etl#26]
Thanks for sharing PHP ETL. I enjoyed the approach to data handling and it helped me migrate between two databases provided by different systems.

 The number of transformers is limited and it seems unreasonable to expect the library to provide something that covers every need.

Would you be interested in a transformer which lets the user provide a callback with an anonymous function á la:

```php

<?php

use Marquine\Etl\Row;
use Marquine\Etl\Transformers\Transformer;

class CallbackTransformer extends Transformer
{

  /** @var callable */
  protected $callback;

  protected $availableOptions = [
    'callback'
  ];

  /**
   * Transform the given row.
   *
   * @param \Marquine\Etl\Row $row
   *
   * @return void
   */
  public function transform(Row $row)
  {
    call_user_func($this->callback, $row);
  }
}
```

**Comment by Naelpuissant** [comment]
I agree ! But I think you can create your own Transformers just by binding it to the container

```
use Marquine\Etl\Container;
use MyTransformer;

$container = Container::getInstance();
$container->bind('my_transformer', MyTransformer::class);
```

**Comment by kasperg** [comment]
You can. Based on my brief experience with PHP-ETL many of my transformations are <5 LOC. I find it a bit excessive to create a class for each.

**Comment by sekjal** [comment]
I've also found this need, and created a Callback Transformer as well (nearly identical code!).  My functions were placed in a single library file for each project, as each was very bespoke to the particular data.

**Comment by ecourtial** [comment]
Hi @kasperg if you want, we forked the library [here](https://github.com/wizaplace/php-etl) and we fixed some issues and added some features. The changelog is available [here](https://github.com/wizaplace/php-etl/blob/master/changelog.MD). Our objective is to keep this great library alive. If you find any bug or want to contribute to keep the package alive, do not hesitate!

**Comment by kasperg** [comment]
@ecourtial :+1: My current use case for `php-etl` has passed but you are welcome to lift my suggestion to your fork.
